# Análise Exploratória dos Dados

## Dicionário de dados

In [1]:
# importar os pacotes necessários
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dicionario = pd.read_csv("../data/raw/dicionario_dados.csv", sep=";")
dicionario

,base,coluna,descricao
0,base_cadastral,id_cliente,Identificador único do cliente
1,base_cadastral,sexo,Sexo do cliente (M ou F)
2,base_cadastral,data_nascimento,Data de nascimento do cliente
3,base_cadastral,qtd_filhos,Quantidade de filhos declarados
4,base_cadastral,qtd_membros_familia,Quantidade total de membros da família
5,base_cadastral,renda_anual,Renda total anual declarada pelo cliente
6,base_cadastral,tipo_renda,"Tipo de fonte de renda (trabalho, pensão, apos..."
7,base_cadastral,ocupacao,Ocupação profissional do cliente
8,base_cadastral,tipo_organizacao,Tipo de empresa onde o cliente trabalha
9,base_cadastral,nivel_educacao,Nível de escolaridade alcançado
10,base_cadastral,estado_civil,Estado civil do cliente
11,base_cadastral,tipo_moradia,"Tipo de moradia (casa própria, alugada, com pa..."
12,base_cadastral,possui_carro,Indicador se o cliente possui carro (Y/N)
13,base_cadastral,possui_imovel,Indicador se o cliente possui imóvel (Y/N)
14,base_cadastral,nota_regiao_cliente,Avaliação de risco da região de residência do ...
15,base_cadastral,nota_regiao_cliente_cidade,"Avaliação de risco da região, ajustada para a ..."
16,base_submissao,id_cliente,Identificador único do cliente
17,base_submissao,data_solicitacao,Data em que o contrato mais recente foi solici...
18,base_submissao,dia_semana_solicitacao,Dia da semana em que o pedido foi iniciado
19,base_submissao,hora_solicitacao,Hora do dia em que a solicitação foi realizada
20,base_submissao,tipo_contrato,Tipo de contrato solicitado (ex: crédito pesso...
21,base_submissao,valor_credito,Valor total do crédito solicitado
22,base_submissao,valor_bem,"Valor do bem financiado, quando aplicável"
23,base_submissao,valor_parcela,Valor da parcela periódica estimada para pagam...
24,historico_emprestimos,id_contrato,Identificador único do contrato de empréstimo
25,historico_emprestimos,id_cliente,Identificador do cliente associado ao contrato
26,historico_emprestimos,tipo_contrato,"Tipo de contrato (crédito pessoal, rotativo, e..."
27,historico_emprestimos,status_contrato,"Status final do contrato (aprovado, recusado, ..."
28,historico_emprestimos,data_decisao,Data em que o contrato foi analisado e aprovad...
29,historico_emprestimos,data_liberacao,Data em que o crédito foi liberado
30,historico_emprestimos,data_primeiro_vencimento,Data prevista para o vencimento da primeira pa...
31,historico_emprestimos,data_ultimo_vencimento_original,Data original prevista para a última parcela
32,historico_emprestimos,data_ultimo_vencimento,Data final revisada da última parcela
33,historico_emprestimos,data_encerramento,Data em que o contrato foi encerrado (por quit...
34,historico_emprestimos,valor_solicitado,Valor inicialmente solicitado pelo cliente
35,historico_emprestimos,valor_credito,Valor efetivamente liberado
36,historico_emprestimos,valor_bem,"Valor do bem adquirido, quando aplicável"
37,historico_emprestimos,valor_parcela,Valor estimado da parcela periódica
38,historico_emprestimos,valor_entrada,Valor pago como entrada
39,historico_emprestimos,percentual_entrada,Percentual da entrada sobre o valor total
40,historico_emprestimos,qtd_parcelas_planejadas,Quantidade de parcelas previstas no contrato
41,historico_emprestimos,taxa_juros_padrao,Taxa de juros padrão aplicada
42,historico_emprestimos,taxa_juros_promocional,Taxa promocional (se aplicável)
43,historico_emprestimos,tipo_pagamento,Forma de pagamento do contrato
44,historico_emprestimos,finalidade_emprestimo,Finalidade declarada para o uso do empréstimo
45,historico_emprestimos,tipo_cliente,"Tipo de cliente (novo, recorrente, etc.)"
46,historico_emprestimos,faixa_rendimento,Categoria de retorno do cliente para o banco
47,historico_emprestimos,tipo_portfolio,"Tipo de portfólio (interno, externo, etc.)"
48,historico_emprestimos,tipo_produto,Tipo de produto financeiro contratado
49,historico_emprestimos,categoria_bem,Categoria do bem financiado
50,historico_emprestimos,combinacao_produto,Combinação de produtos oferecida
51,historico_emprestimos,setor_vendedor,Setor da empresa vendedora
52,historico_emprestimos,canal_venda,Canal utilizado para originação da venda
53,historico_emprestimos,area_venda,Área ou localização da venda
54,historico_emprestimos,dia_semana_solicitacao,Dia da semana em que a solicitação foi iniciada
55,historico_emprestimos,hora_solicitacao,Hora do dia em que a solicitação foi iniciada
56,historico_emprestimos,flag_ultima_solicitacao_contrato,Indica se foi a última solicitação para aquele...
57,historico_emprestimos,flag_ultima_solicitacao_dia,Indica se foi a última solicitação feita no me...
58,historico_emprestimos,motivo_recusa,"Motivo da recusa, quando o contrato foi negado"
59,historico_emprestimos,acompanhantes_cliente,Tipo de acompanhantes no momento da solicitaçã...
60,historico_emprestimos,flag_seguro_contratado,Indica se o cliente contratou seguro junto com...
61,historico_parcelas,id_contrato,Identificador do contrato de empréstimo
62,historico_parcelas,id_cliente,Identificador do cliente
63,historico_parcelas,versao_parcela,Versão da parcela dentro do contrato (caso haj...
64,historico_parcelas,numero_parcela,Número sequencial da parcela dentro do contrato
65,historico_parcelas,data_prevista_pagamento,Data inicialmente prevista para o pagamento da...
66,historico_parcelas,data_real_pagamento,Data real em que o pagamento foi efetuado
67,historico_parcelas,valor_previsto_parcela,Valor original previsto da parcela
68,historico_parcelas,valor_pago_parcela,Valor efetivamente pago pelo cliente

## Funções

## Criação das Métricas Históricas

In [3]:
# importar as tabelas
cadastral = pd.read_parquet('../data/raw/base_cadastral.parquet', engine="fastparquet")
submissao = pd.read_parquet('../data/raw/base_submissao.parquet', engine="fastparquet") 
hist_contratos = pd.read_parquet('../data/raw/historico_emprestimos.parquet', engine="fastparquet")
hist_parcelas = pd.read_parquet('../data/raw/historico_parcelas.parquet', engine="fastparquet")

In [4]:
submissao.head()

,id_cliente,data_solicitacao,dia_semana_solicitacao,hora_solicitacao,tipo_contrato,valor_credito,valor_bem,valor_parcela
0,100023,2025-02-24,MONDAY,12,Cash loans,544491.0,454500.0,17563.5
1,100031,2025-02-17,MONDAY,9,Cash loans,979992.0,702000.0,27076.5
2,100056,2025-02-20,THURSDAY,10,Cash loans,1506816.0,1350000.0,49927.5
3,100069,2025-02-10,MONDAY,11,Cash loans,640458.0,517500.0,27265.5
4,100085,2025-02-19,WEDNESDAY,12,Cash loans,755190.0,675000.0,28894.5

In [5]:
cadastral.head()

,id_cliente,sexo,data_nascimento,qtd_filhos,qtd_membros_familia,renda_anual,tipo_renda,ocupacao,tipo_organizacao,nivel_educacao,estado_civil,tipo_moradia,possui_carro,possui_imovel,nota_regiao_cliente,nota_regiao_cliente_cidade
0,100023,F,1994-01-30,1,2.0,90000.0,State servant,Core staff,Kindergarten,Higher education,Single / not married,House / apartment,N,Y,2,2
1,100031,F,1973-11-13,0,1.0,112500.0,Working,Cooking staff,Business Entity Type 3,Secondary / secondary special,Widow,House / apartment,N,Y,3,2
2,100056,M,1975-02-19,0,2.0,360000.0,Working,Laborers,Transport: type 2,Secondary / secondary special,Married,House / apartment,Y,Y,2,2
3,100069,M,1986-04-10,1,2.0,360000.0,Working,Laborers,Transport: type 4,Secondary / secondary special,Separated,House / apartment,Y,Y,2,2
4,100085,M,1994-07-05,1,3.0,157500.0,Working,Drivers,Business Entity Type 1,Secondary / secondary special,Married,House / apartment,N,Y,2,2

In [6]:
cadastral.info()

<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id_cliente                  40000 non-null  int64
 1   sexo                        40000 non-null  object
 2   data_nascimento             40000 non-null  object
 3   qtd_filhos                  40000 non-null  int64
 4   qtd_membros_familia         40000 non-null  float64
 5   renda_anual                 40000 non-null  float64
 6   tipo_renda                  40000 non-null  object
 7   ocupacao                    27324 non-null  object
 8   tipo_organizacao            40000 non-null  object
 9   nivel_educacao              40000 non-null  object
 10  estado_civil                40000 non-null  object
 11  tipo_moradia                40000 non-null  object
 12  possui_carro                40000 non-null  object
 13  possui_imovel               40000 non-null  object
 14  nota_regiao_cliente         40000 non-null  int64
 15  nota_regiao_cliente_cidade  40000 non-null  int64
dtypes: float64(2), int64(4), object(10)
memory usage: 4.9+ MB

In [ ]:
# unir historico de contratos com parcelas
hist_total = hist_contratos.merge(
    hist_parcelas, 
    how="left", 
    on=["id_contrato", "id_cliente"]
)

hist_total["dias_atraso_parcela"] = (pd.to_datetime(hist_total["data_real_pagamento"]) - pd.to_datetime(hist_total["data_prevista_pagamento"])).dt.days

# CRIACAO DA VARIÁVEL ALVO DE ACORDO COM O REGULADOR (BACEN)
hist_total["target"] = np.where(
    hist_total["dias_atraso_parcela"] > 90,
    1,
    0
)

features_temp = hist_total.groupby(
    [
        "id_cliente",
        "id_contrato", 
        "tipo_contrato", 
        "status_contrato", 
        "data_decisao", 
        "valor_credito", 
        "valor_bem", 
        "percentual_entrada",
        "qtd_parcelas_planejadas",
        "tipo_pagamento",
        "finalidade_emprestimo",
        "tipo_cliente",
        "faixa_rendimento",
        "tipo_portfolio",
        "tipo_produto",
        "categoria_bem",
        "combinacao_produto",
        "setor_vendedor",
        "dia_semana_solicitacao",
        "hora_solicitacao",
        "flag_ultima_solicitacao_contrato",
        "flag_ultima_solicitacao_dia",
        "motivo_recusa",
        "acompanhantes_cliente",
        "flag_seguro_contratado"
    ]
).agg(
num_max_parcelas=("numero_parcela", "max"),
# num_max_atraso_contrato=("dias_atraso_parcela", "max"),
valor_total_a_pagar=("valor_parcela", "sum"),
valor_medio_pago_contrato=("valor_pago_parcela", "mean"),
valor_max_pago_contrato=("valor_pago_parcela", "max"),
target=("target", "max"),
).reset_index()

features_temp = features_temp.sort_values(by=["id_cliente", "data_decisao"])

In [13]:
features_temp.loc[features_temp["data_decisao"] > "2025-01-01"].head()

,id_cliente,id_contrato,tipo_contrato,status_contrato,data_decisao,valor_credito,valor_bem,percentual_entrada,qtd_parcelas_planejadas,tipo_pagamento,finalidade_emprestimo,tipo_cliente,faixa_rendimento,tipo_portfolio,tipo_produto,categoria_bem,combinacao_produto,setor_vendedor,dia_semana_solicitacao,hora_solicitacao,flag_ultima_solicitacao_contrato,flag_ultima_solicitacao_dia,motivo_recusa,acompanhantes_cliente,flag_seguro_contratado,qtd_contratos,num_max_parcelas,valor_total_a_pagar,valor_medio_pago_contrato,valor_max_pago_contrato,target
31,100278,1770201,Consumer loans,Approved,2025-01-03,133038.0,130455.0,0.100334,10.0,XNA,XAP,New,middle,POS,XNA,Consumer Electronics,POS household with interest,Consumer electronics,FRIDAY,11,Y,1,XAP,Unaccompanied,1.0,1,NaN,15654.690,NaN,NaN,0
72,100471,1153218,Consumer loans,Approved,2025-01-22,202455.0,202455.0,0.000000,18.0,XNA,XAP,Refreshed,middle,POS,XNA,Furniture,POS industry with interest,Furniture,WEDNESDAY,16,Y,1,XAP,Unaccompanied,0.0,1,NaN,14607.135,NaN,NaN,0
172,101205,2628025,Consumer loans,Approved,2025-02-07,36787.5,31756.5,0.000000,12.0,Cash through the bank,XAP,Repeater,high,POS,XNA,Mobile,POS mobile with interest,Connectivity,FRIDAY,12,Y,1,XAP,"Spouse, partner",1.0,1,NaN,4603.500,NaN,NaN,0
231,101583,2173085,Consumer loans,Approved,2025-01-03,350559.0,350559.0,0.000000,6.0,Cash through the bank,XAP,Repeater,low_action,POS,XNA,Furniture,POS industry without interest,Furniture,FRIDAY,16,Y,1,XAP,Unaccompanied,0.0,1,1.0,61632.585,61632.585,61632.585,0
272,101942,1031150,Consumer loans,Approved,2025-02-06,48208.5,44671.5,0.000000,6.0,Cash through the bank,XAP,Repeater,middle,POS,XNA,Audio/Video,POS household with interest,Consumer electronics,THURSDAY,9,Y,1,XAP,Family,1.0,1,NaN,9045.225,NaN,NaN,0

In [18]:
a = features_temp[[
    "id_cliente",
    "data_decisao"
]]

In [19]:
teste = submissao.merge(a, how="left", on="id_cliente")

teste.head()

,id_cliente,data_solicitacao,dia_semana_solicitacao,hora_solicitacao,tipo_contrato,valor_credito,valor_bem,valor_parcela,data_decisao
0,100023,2025-02-24,MONDAY,12,Cash loans,544491.0,454500.0,17563.5,2018-07-07
1,100023,2025-02-24,MONDAY,12,Cash loans,544491.0,454500.0,17563.5,2020-02-01
2,100031,2025-02-17,MONDAY,9,Cash loans,979992.0,702000.0,27076.5,NaN
3,100056,2025-02-20,THURSDAY,10,Cash loans,1506816.0,1350000.0,49927.5,NaN
4,100069,2025-02-10,MONDAY,11,Cash loans,640458.0,517500.0,27265.5,2020-11-07

In [20]:
teste.info()

<class 'pandas.DataFrame'>
RangeIndex: 60904 entries, 0 to 60903
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_cliente              60904 non-null  int64
 1   data_solicitacao        60904 non-null  object
 2   dia_semana_solicitacao  60904 non-null  object
 3   hora_solicitacao        60904 non-null  int64
 4   tipo_contrato           60904 non-null  object
 5   valor_credito           60904 non-null  float64
 6   valor_bem               60867 non-null  float64
 7   valor_parcela           60895 non-null  float64
 8   data_decisao            48223 non-null  str
dtypes: float64(3), int64(2), object(3), str(1)
memory usage: 4.2+ MB

In [23]:
teste.loc[
    teste["data_decisao"] == teste.groupby("id_cliente")["data_decisao"].transform("max")
].head(50)

,id_cliente,data_solicitacao,dia_semana_solicitacao,hora_solicitacao,tipo_contrato,valor_credito,valor_bem,valor_parcela,data_decisao
1,100023,2025-02-24,MONDAY,12,Cash loans,544491.0,454500.0,17563.5,2020-02-01
7,100069,2025-02-10,MONDAY,11,Cash loans,640458.0,517500.0,27265.5,2023-03-26
8,100085,2025-02-19,WEDNESDAY,12,Cash loans,755190.0,675000.0,28894.5,2021-12-02
9,100098,2025-02-05,WEDNESDAY,9,Revolving loans,270000.0,270000.0,13500.0,2017-11-28
10,100104,2025-02-19,WEDNESDAY,17,Cash loans,547344.0,472500.0,30690.0,2018-01-16
14,100111,2025-02-17,MONDAY,11,Cash loans,862560.0,720000.0,27954.0,2023-06-07
15,100123,2025-02-15,SATURDAY,16,Cash loans,675000.0,675000.0,19737.0,2020-07-02
17,100165,2025-02-04,TUESDAY,16,Cash loans,1293502.5,1129500.0,35568.0,2020-11-03
21,100208,2025-02-21,FRIDAY,11,Cash loans,888840.0,675000.0,29016.0,2022-01-21
24,100233,2025-02-05,WEDNESDAY,10,Cash loans,679671.0,607500.0,28926.0,2024-12-16
26,100258,2025-02-18,TUESDAY,14,Cash loans,81000.0,81000.0,9135.0,2024-02-20
27,100265,2025-02-04,TUESDAY,15,Cash loans,723996.0,585000.0,34960.5,2022-11-27
28,100266,2025-02-21,FRIDAY,17,Cash loans,1256400.0,900000.0,36864.0,2021-05-05
29,100276,2025-02-08,SATURDAY,11,Cash loans,497520.0,450000.0,39438.0,2019-11-30
32,100281,2025-02-13,THURSDAY,15,Cash loans,675000.0,675000.0,21906.0,2021-03-28
34,100298,2025-02-06,THURSDAY,10,Cash loans,473760.0,450000.0,48676.5,2022-03-15
36,100301,2025-02-10,MONDAY,11,Cash loans,571486.5,454500.0,31131.0,2024-10-05
42,100307,2025-02-10,MONDAY,11,Cash loans,451804.5,369000.0,35824.5,2022-10-18
48,100317,2025-02-05,WEDNESDAY,12,Cash loans,630000.0,630000.0,30438.0,2020-06-10
50,100332,2025-02-13,THURSDAY,13,Cash loans,545040.0,450000.0,20677.5,2019-03-22
51,100341,2025-02-18,TUESDAY,10,Cash loans,545040.0,450000.0,20677.5,2018-10-12
52,100342,2025-02-13,THURSDAY,15,Cash loans,101880.0,90000.0,10827.0,2022-02-05
55,100374,2025-02-12,WEDNESDAY,6,Cash loans,1308964.5,1143000.0,42354.0,2020-03-10
56,100403,2025-02-19,WEDNESDAY,14,Cash loans,1350000.0,1350000.0,39604.5,2022-05-22
59,100406,2025-02-07,FRIDAY,8,Cash loans,468648.0,414000.0,34101.0,2024-07-18
60,100410,2025-02-20,THURSDAY,17,Cash loans,1258650.0,1125000.0,56277.0,2018-05-27
62,100418,2025-02-21,FRIDAY,17,Cash loans,521280.0,450000.0,31500.0,2022-12-12
63,100437,2025-02-06,THURSDAY,13,Cash loans,817560.0,675000.0,30951.0,2017-08-14
64,100449,2025-02-14,FRIDAY,9,Cash loans,942300.0,675000.0,27679.5,2022-10-19
65,100458,2025-02-06,THURSDAY,8,Cash loans,808650.0,675000.0,26217.0,2024-06-13
66,100459,2025-02-13,THURSDAY,10,Revolving loans,225000.0,225000.0,11250.0,2022-04-19
67,100462,2025-02-05,WEDNESDAY,11,Cash loans,152820.0,135000.0,7911.0,2018-05-10
68,100471,2025-02-15,SATURDAY,16,Cash loans,697500.0,697500.0,35743.5,2025-01-22
69,100493,2025-02-06,THURSDAY,11,Cash loans,1288350.0,1125000.0,41692.5,2017-05-25
74,100498,2025-02-12,WEDNESDAY,6,Cash loans,485190.0,405000.0,24903.0,2022-12-06
78,100521,2025-02-14,FRIDAY,13,Revolving loans,225000.0,225000.0,11250.0,2024-04-28
79,100525,2025-02-10,MONDAY,12,Cash loans,215640.0,180000.0,11421.0,2022-01-16
80,100562,2025-02-08,SATURDAY,11,Revolving loans,675000.0,675000.0,33750.0,2022-05-11
88,100675,2025-02-18,TUESDAY,7,Cash loans,1125000.0,1125000.0,33025.5,2021-05-27
89,100678,2025-02-11,TUESDAY,9,Cash loans,1078200.0,900000.0,31522.5,2020-02-15
90,100685,2025-02-21,FRIDAY,11,Cash loans,360000.0,360000.0,23134.5,2020-08-29
91,100693,2025-02-20,THURSDAY,16,Cash loans,808650.0,675000.0,26217.0,2023-02-01
92,100712,2025-02-05,WEDNESDAY,11,Cash loans,1575000.0,1575000.0,43443.0,2017-06-10
99,100746,2025-02-09,SUNDAY,12,Revolving loans,495000.0,495000.0,24750.0,2024-04-15
100,100759,2025-02-12,WEDNESDAY,14,Cash loans,938304.0,810000.0,50121.0,2019-07-17
102,100783,2025-02-13,THURSDAY,11,Revolving loans,180000.0,180000.0,9000.0,2024-08-18
105,100785,2025-02-22,SATURDAY,8,Cash loans,293535.0,265500.0,18085.5,2020-03-17
107,100806,2025-02-07,FRIDAY,11,Cash loans,654498.0,585000.0,26086.5,2022-11-25
112,100813,2025-02-14,FRIDAY,14,Cash loans,635962.5,549000.0,21865.5,2022-09-29
114,100815,2025-02-13,THURSDAY,10,Cash loans,225000.0,225000.0,12694.5,2020-09-24